import Script from "next/script";

export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <Script
        id="fontawesome"
        src="https://kit.fontawesome.com/c6bd86d823.js"
      />
    </>
  );
}
