#!/bin/zsh

# Set Session Name
SESSION_NAME=$(basename $(dirname $(pwd)))
SESSION_EXISTS=$(tmux list-sessions | egrep "^${SESSION_NAME}$")

#set -e
#set -x

if [ -f .node-version ]; then
  echo "node=$(cat .node-version)"
  export NVM_DIR=$HOME/.nvm;
  source $NVM_DIR/nvm.sh;
  nvm use $(cat .node-version)
fi

if [ -f .ruby-version ]; then
  echo "ruby=$(cat .ruby-version)"
  echo .ruby-version
  eval "$(rbenv init -)"
  rbenv shell $(cat .ruby-version)
fi


# Only create tmux session if it doesn't already exist
if [ "$SESSION_EXISTS" = "" ]
then
    # Start New Session with our name
    tmux new-session -d -s "${SESSION_NAME}"

    # fe
    tmux rename-window -t 0 'fe'
    tmux send-keys -t 'fe' './fe/script/dev' C-m 'clear' C-m # Switch to bind script?

    # be
    tmux new-window -t $SESSION_NAME:1 -n 'be'
    tmux send-keys -t 'be' './be/script/dev' C-m # Switch to bind script?
fi

# Attach Session, on the Main window
tmux attach-session -t $SESSION_NAME:0
