services:
  - type: web
    name: mtf
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    disk:
      name: Data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.4.0
      - key: DATABASE_FILENAME
        value: /data/strapi/production/sqlite.db
      - key: PUBLIC_DIRECTORY
        value: /data/strapi/production/public
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: API_TOKEN_SALT
        generateValue: true
        sync: false
      - key: APP_KEYS
        generateValue: true
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
